# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 今日头条极速版

on:
  workflow_dispatch:
  schedule:
    - cron: '5,35 0-15 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【今日头条极速版】'
        run: |
          node jrtt.js
        env:
          JRTTSIGNURL: ${{ secrets.JRTTSIGNURL }}
          JRTTSIGNKEY: ${{ secrets.JRTTSIGNKEY }}
          JRTTFARMURL: ${{ secrets.JRTTFARMURL }}
          JRTTFARMKEY: ${{ secrets.JRTTFARMKEY }}
          JRTTREADURL: ${{ secrets.JRTTREADURL }}
          JRTTREADKEY: ${{ secrets.JRTTREADKEY }}
          JRTTCOLLECT: ${{ secrets.JRTTCOLLECT }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}